#! /bin/bash
echo "************************************"
echo
echo "---------BUTTON/SWITCH TEST--------"
echo
echo "***********************************"
echo

# Export GPIO pin 76
echo 76 > /sys/class/gpio/export

echo "Status of Button: "

# Read the value of the GPIO pin
status=$(cat /sys/class/gpio/PC12/value)

if [ "$status" -eq 0 ]
 then
    echo "Button pressed"
    echo
    echo "******** PASS *********"
    echo
 echo                                
else                              
    echo "Button pressed"         
    echo                          
    echo "******** FAIL *********"
    echo                          
fi        
