#!/bin/bash
echo "***************************************************"
echo
echo "------------------ DIN TEST -----------------------"
echo
echo "***************************************************"
echo
echo
echo 84 > /sys/class/gpio/export
if [ -d "/sys/class/gpio/PC20" ]
then
    echo "GPIO Exported"
else
    echo "GPIO Export Failed"
fi
echo in > /sys/class/gpio/PC20/direction
sleep 2
gpio5_value=$(cat /sys/class/gpio/PC20/value)
if [ "$gpio5_value" == 1 ]
then
    echo
    echo "============= PASS ==============="
    echo
else                                         
    echo                                     
    echo "============= FAIL ================"
    echo                                      
fi                                            
       
