#! /bin/bash
echo "************************************"
echo                                      
echo "------------- LED2 TEST------------"
echo                                      
echo "***********************************"
echo                                     
                                         
echo 81 > /sys/class/gpio/export         
                                         
echo "GPIO EXPORTED: "                   
echo out > /sys/class/gpio/PC17/direction
status=$(cat /sys/class/gpio/PC17/value)
                                       
if [ "$status" -eq 0 ]                 
 then                                  
    echo 0 > /sys/class/gpio/PC17/value
    echo " LED1 ON "              
    echo                          
    echo "******** PASS *********"
    echo            
else                                    
 echo "LED 2 NOT FOUND "               
    echo                               
    echo "******** FAIL *********"     
    echo                               
fi        
